### ISSUE TITLE
Error on parking telescope

### ISSUE THREAD

**Issue by thusser** [pyobs/pyobs-core#111]
2022-03-02 02:50:27,507 [INFO] telescope.py:271 Reached destination.
2022-03-02 02:51:07,005 [WARNING] weatheraware.py:57 Received bad weather event, shutting down.
2022-03-02 02:51:07,006 [INFO] telescope.py:136 Parking telescope...
2022-03-02 02:51:28,033 [ERROR] rootstanza.py:85 Error handling {jabber:client}iq stanza
Traceback (most recent call last):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 886, in handler_callback_routine
    await cb(data)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/slixmpp/rpc.py", line 123, in _on_jabber_rpc_method_call
    return_value = await self._handler.execute(pmethod, *params, sender=iq["from"].user)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/modules/module.py", line 261, in execute
    response = await func(*func_args, **ba.arguments, **func_kwargs)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs_alpaca/telescope.py", line 232, in set_offsets_radec
    async with LockWithAbort(self._lock_moving, self._abort_move):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/utils/threads/lockwithabort.py", line 38, in __aenter__
    raise AcquireLockFailed()
pyobs.utils.threads.lockwithabort.AcquireLockFailed
2022-03-02 02:51:28,042 [ERROR] basexmpp.py:796 
Traceback (most recent call last):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 886, in handler_callback_routine
    await cb(data)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/slixmpp/rpc.py", line 123, in _on_jabber_rpc_method_call
    return_value = await self._handler.execute(pmethod, *params, sender=iq["from"].user)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/modules/module.py", line 261, in execute
    response = await func(*func_args, **ba.arguments, **func_kwargs)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs_alpaca/telescope.py", line 232, in set_offsets_radec
    async with LockWithAbort(self._lock_moving, self._abort_move):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/utils/threads/lockwithabort.py", line 38, in __aenter__
    raise AcquireLockFailed()
pyobs.utils.threads.lockwithabort.AcquireLockFailed
2022-03-02 02:51:28,043 [ERROR] base_events.py:1738 Task exception was never retrieved
future: <Task finished name='Task-497499' coro=<XMLStream.event.<locals>.handler_callback_routine() done, defined at /opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py:884> exception=TypeError("unsupported operand type(s) for %: 'AcquireLockFailed' and 'tuple'")>
Traceback (most recent call last):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 886, in handler_callback_routine
    await cb(data)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/slixmpp/rpc.py", line 123, in _on_jabber_rpc_method_call
    return_value = await self._handler.execute(pmethod, *params, sender=iq["from"].user)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/modules/module.py", line 261, in execute
    response = await func(*func_args, **ba.arguments, **func_kwargs)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs_alpaca/telescope.py", line 232, in set_offsets_radec
    async with LockWithAbort(self._lock_moving, self._abort_move):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/utils/threads/lockwithabort.py", line 38, in __aenter__
    raise AcquireLockFailed()
pyobs.utils.threads.lockwithabort.AcquireLockFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 889, in handler_callback_routine
    old_exception(e)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/stanza/rootstanza.py", line 88, in exception
    self.stream.exception(e)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/basexmpp.py", line 796, in exception
    log.exception(exception)
  File "/usr/lib/python3.9/logging/__init__.py", line 1477, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1471, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/commlogging.py", line 30, in emit
    rec.created, rec.levelname, os.path.basename(rec.pathname), rec.funcName, rec.lineno, rec.msg % rec.args
TypeError: unsupported operand type(s) for %: 'AcquireLockFailed' and 'tuple'
2022-03-02 02:51:28,044 [ERROR] base_events.py:1771 Exception in default exception handler
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1764, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1738, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/lib/python3.9/logging/__init__.py", line 1471, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/commlogging.py", line 30, in emit
    rec.created, rec.levelname, os.path.basename(rec.pathname), rec.funcName, rec.lineno, rec.msg % rec.args
TypeError: not enough arguments for format string
2022-03-02 02:51:44,030 [INFO] telescope.py:144 Telescope parked.
2022-03-02 04:41:10,944 [INFO] weatheraware.py:121 Weather seems to be bad, shutting down.
2022-03-02 04:41:10,946 [INFO] telescope.py:136 Parking telescope...
2022-03-02 04:41:12,938 [INFO] telescope.py:144 Telescope parked.

**Comment by thusser** [comment]
Probably go here in AlpacaTelescope:

```
                # TODO: add abort event
                await self._device.put("Park", timeout=60)
                await self._change_motion_status(MotionStatus.PARKED)
                log.info("Telescope parked.")
```

Call Park in background and wait until abort event is set or AtPark is true.
