### ISSUE TITLE
ValueError logging

### ISSUE THREAD

**Issue by thusser** [pyobs/pyobs-core#114]
```
ValueError: New focus out of bounds: 4.632+-0.139mm.
2022-03-11 18:34:00,081 [ERROR] base_events.py:1738 Task exception was never retrieved
future: <Task finished name='Task-276' coro=<XMLStream.event.<locals>.handler_callback_routine() done, defined at /opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py:884> exception=TypeError("unsupported operand type(s) for %: 'ValueError' and 'tuple'")>
Traceback (most recent call last):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 886, in handler_callback_routine
    await cb(data)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/slixmpp/rpc.py", line 123, in _on_jabber_rpc_method_call
    return_value = await self._handler.execute(pmethod, *params, sender=iq["from"].user)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/modules/module.py", line 261, in execute
    response = await func(*func_args, **ba.arguments, **func_kwargs)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/modules/focus/focusseries.py", line 191, in auto_focus
    focus = self._series.fit_focus()
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/utils/focusseries/projection.py", line 136, in fit_focus
    raise ValueError("New focus out of bounds: {0:.3f}+-{1:.3f}mm.".format(foc, err))
ValueError: New focus out of bounds: 4.632+-0.139mm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 889, in handler_callback_routine
    old_exception(e)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/stanza/rootstanza.py", line 88, in exception
    self.stream.exception(e)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/slixmpp/basexmpp.py", line 796, in exception
    log.exception(exception)
  File "/usr/lib/python3.9/logging/__init__.py", line 1477, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1471, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/commlogging.py", line 30, in emit
    rec.created, rec.levelname, os.path.basename(rec.pathname), rec.funcName, rec.lineno, rec.msg % rec.args
TypeError: unsupported operand type(s) for %: 'ValueError' and 'tuple'
2022-03-11 18:34:00,122 [ERROR] base_events.py:1771 Exception in default exception handler
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1764, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1738, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/lib/python3.9/logging/__init__.py", line 1471, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/opt/pyobs/venv/lib/python3.9/site-packages/pyobs/comm/commlogging.py", line 30, in emit
    rec.created, rec.levelname, os.path.basename(rec.pathname), rec.funcName, rec.lineno, rec.msg % rec.args
TypeError: not enough arguments for format string

```

**Comment by thusser** [comment]
Use Formatter to do `rec.msg % rec.args`:
https://docs.python.org/3/library/logging.html#logging.Formatter
