### ISSUE TITLE
gui crashes when moving telescope without coordinates given

### ISSUE THREAD

**Issue by masurt** [pyobs/pyobs-core#14]
```
Traceback (most recent call last):
  File "/home/tilman/autoguiding/autoguiding/lib/python3.7/site-packages/pyobs_gui/widgettelescope.py", line 224, in move
    coords = SkyCoord(ra + ' ' + dec, frame=ICRS, unit=(u.hour, u.deg))
  File "/home/tilman/autoguiding/autoguiding/lib/python3.7/site-packages/astropy/coordinates/sky_coordinate.py", line 274, in __init__
    raise ValueError('Cannot create a SkyCoord without data')
ValueError: Cannot create a SkyCoord without data
```

**Comment by thusser** [comment]
fixed
